version: '3'

services:
    nginx:
        build:
            context: docker/nginx
            dockerfile: Dockerfile
            args:
                - NGINXUSER=${NGINXUSER:-www-data}
                - NGINXGROUP=${NGINXGROUP:-www-data}
        container_name: nginx
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - .:/var/www/html:delegated
        restart: unless-stopped
        depends_on:
            - reminder.backend
            - reminder.redis
        networks:
            - reminder.network

    reminder.backend:
        build:
            context: .
            dockerfile: laravel.dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        container_name: reminder.backend
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        restart: unless-stopped
        networks:
            - reminder.network
        depends_on:
            - reminder.redis
            - reminder.mysql

    reminder.scheduler:
        build:
            context: .
            dockerfile: scheduler.dockerfile
        container_name: reminder.scheduler
        volumes:
            - '.:/var/www/html'
        restart: unless-stopped
        networks:
            - reminder.network
        depends_on:
            - reminder.redis
            - reminder.backend
            - reminder.mysql

    reminder.redis:
        image: redis:alpine
        container_name: reminder.redis
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'reminder.redis.vol:/data'
        restart: unless-stopped
        networks:
            - reminder.network
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]

    reminder.memcached:
        image: memcached:alpine
        ports:
            - '11211:11211'
        restart: unless-stopped
        networks:
            - reminder.network

    reminder.meiliserach:
        image: getmeili/meilisearch:latest
        container_name: reminder.meiliserach
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'reminder.meilisearch.vol:/data.ms'
        restart: unless-stopped
        networks:
            - reminder.network

    reminder.mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: reminder.mysql
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'reminder.mysql.vol:/var/lib/mysql'
        networks:
            - reminder.network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s


networks:
    reminder.network:
        driver: bridge

volumes:
    reminder.mysql.vol:
        driver: local
    reminder.redis.vol:
        driver: local
    reminder.meilisearch.vol:
        driver: local
